
on:
  workflow_call:
    inputs:
      eid:
        required: true
        type: string
      oid:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true
      THREATRIX_SERVER_API_KEY:
        required: true
jobs:
  scan-repository:
    name: Scan repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Run scan with threat-agent
        uses: rmashchenko/threat-agent-scan@main
        with:
          eid: ${{ inputs.eid }}
          oid: ${{ inputs.oid }}
          server-url: 'https://app.threatrix.io'
          scm-token: ${{ secrets.TOKEN }}
          api-token: ${{ secrets.THREATRIX_SERVER_API_KEY }}
          app-name: ${{ github.repository }}
          branch: ${{ github.ref_name }}