
on:
  workflow_call:
    inputs:
      eid:
        required: true
        type: string
      oid:
        required: true
        type: string
      app-name:
        required: false
        type: string
        default: ${{ github.repository }}
      trx-url:
        required: false
        type: string
        default: 'https://app.threatrix.io'
    secrets:
      TOKEN:
        required: true
      THREATRIX_SERVER_API_KEY:
        required: true
jobs:
  scan-repository:
    name: Scan repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Run scan with threat-agent
        uses: threatrix/threat-agent-scan@master
        with:
          eid: ${{ inputs.eid }}
          oid: ${{ inputs.oid }}
          server-url: ${{ inputs.trx-url }}
          scm-token: ${{ secrets.TOKEN }}
          api-token: ${{ secrets.THREATRIX_SERVER_API_KEY }}
          app-name: ${{ inputs.app-name }}
          branch: ${{ github.ref_name }}
